version: "3.3"
   
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - voctiv-test-nw

  web:
    container_name: web
    build: .
    command: flask run
    volumes:
      - .:/code
    depends_on:
      - db
    networks:
      - voctiv-test-nw
  nginx:
    image: nginx:latest
    container_name: my_nginx
    volumes:
      - ./reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 9000:9000
    depends_on:
     - web
    networks:
      - voctiv-test-nw
networks:
  voctiv-test-nw:
    driver: bridge